Changed register page background
ContriHUB/Sheher pull request #30
Opened 2022-10-17 06:26 UTC by kunal2812

Fixes #21 

![image](https://user-images.githubusercontent.com/59749539/196103844-0e12132c-bedc-463c-b3fc-150d0179580f.png)

2022-10-22 18:52 UTC, CyrilMishra commented
> Fixes #21
> 
> ![image](https://user-images.githubusercontent.com/59749539/196103844-0e12132c-bedc-463c-b3fc-150d0179580f.png)

Use css to change multiple background images and try to put images in respect to Indian Tourism Places.
Currently you had used a single image.
Always remember to "Fetch Origin" first.

2022-10-22 18:53 UTC, CyrilMishra requested changes
Use css to change multiple background images and try to put images in respect to Indian Tourism Places.
Currently you had used a single image.
Always remember to "Fetch Origin" first.

2022-10-22 18:53 UTC, CyrilMishra commented on templates/home/register.html
> +          body{
Use css to change multiple background images and try to put images in respect to Indian Tourism Places.
Currently you had used a single image.
Always remember to "Fetch Origin" first.

2022-10-23 13:31 UTC, kunal2812 commented
> 
> Use css to change multiple background images and try to put images in respect to Indian Tourism Places. Currently you had used a single image. Always remember to "Fetch Origin" first.

@CyrilMishra Fixed

2022-10-25 15:31 UTC, merged